version: '2'

services:
  web:
    build: .
    env_file: .env
    ports:
      - '8000:8000'
    volumes:
      - .:/var/www/roll-up-the-stats/src
      - /var/www/roll-up-the-stats/src/node_modules
