version: '2'

services:
  web:
    build: .
    env_file: .env
    ports:
      - '3333:3333'
    volumes:
      - .:/var/www/roll-up-the-stats-server/src
      - /var/www/roll-up-the-stats-server/src/node_modules
      - /var/www/roll-up-the-stats-server/src/data
