export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE'
export const SIGNUP_RESEND_FAILURE = 'SIGNUP_RESEND_FAILURE'
export const VERIFY_EMAIL_ERROR = 'VERIFY_EMAIL_ERROR'
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE'

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD'
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_ERROR'
export const VERIFY_RESET_PASSWORD_SUCCESS = 'VERIFY_RESET_PASSWORD_SUCCESS'
export const VERIFY_RESET_PASSWORD_FAILURE = 'VERIFY_RESET_PASSWORD_FAILURE'

export const AUTH_USER = 'AUTH_USER'
export const UNAUTH_USER = 'UNAUTH_USER'

export const FETCH_ENTRIES = 'FETCH_ENTRIES'
export const ENTRY_SUCCESS = 'ENTRY_SUCCESS'
export const ENTRY_FAILURE = 'ENTRY_FAILURE'

export const SET_REDIRECT_URL = 'SET_REDIRECT_URL'
